# Generated by Django 4.1 on 2024-10-29 16:23

from cinema.models import movie_image_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(null=True, upload_to=movie_image_path),
        ),
    ]
